---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    assignees:
      - ViBiOh
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - ViBiOh
  - package-ecosystem: npm
    directory: /sample/tdd/
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - ViBiOh
  - package-ecosystem: maven
    directory: /sample/java/
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - ViBiOh
