apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: l3miage-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.16'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: l3miage-algolia
    extraLabels:
      k8s-cleaner: 'true'
    image:
      name: vibioh/l3miage
      tag: '202207130946' # {"$imagepolicy": "default:flux-l3miage-web:tag"}
    command:
      - /revealgolia
      - -source
      - /www/doc/genie.md
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgCzttKaykrwEfOPUzSFPgKsT6MWnNx/V3E97sfb4C489EW7FS6jqZfbWWby596nqi8kAjIUiobWFd/WfV/cMHmTqe1Wgkkuu2w5bbi/p9To6tdVbt+WCIL1Vj1Vqz3jXuSPQ6m3z65KTQcM7trGcuW7F7AUfGWXuTSvZrQXVjZbsi1yl9em+L31fDi0u+jMSHqlHwYqyIPdKai5ZiDehL9edo5P0ziuQqUcbtBz8Xx9ZKGJmbCflXbGVMsXUoqk/wcxg2qveetK72sRlXcFCN5WPLmrmFgVdn/jcZ79ScGoMLZqQkgqHJUfWqYw0y8JvTGkiHaf7G+OM7AXqqTdonBBwTOh1TUS4g4sgG6+r62KhPAFxn1IkG9sypDCOvyB5KbuqtX93nIzZ3jQvlZ5gXpHV0r4xqn6dBlYE31qoBhQXSI3heNQFXx8jyWCcE6n/D2YcCMKdVgONgOAREjW8MsW17Ti7CrPixdT0zXADPj8FTaAbQSUeqYikjznrd1NZsbyVoJG+aEDkLGbJ67tUc+4AN/wXJTd+g7FttcZ2VsJiUlBc/+WShC2WM9HDyS59EKfzgzht3S6R7Ms8+wf5291oHx/ENawkBobtkXGSK7YS80jUmRLJMzkAiaqhuSAZaqmDfcscDpBXWgftuiGR8JmFDEfvLN7VT8NQcGz1/FxEL47GKt9lC57jeq2GXSxmecAnX+GqyrJINAj
      REVEALGOLIA_INDEX: AgBIlMm2wV4vgduWD79RtmP4qTk71kkaGwv54KYFmLfVLnUAWJckUT2b7VsAVa+N428QuW4KEm9GSoxXLs+wsVXfuw7rlXMdotQlYxUkgmYqB+L3nUAWaDnJXyeN04HL0YX1Ttk+4E9gtm/fQcs09Qi62gzohWmiTdNck6O3mWHvOEXRDjjGXs3yrLWD24do8d3ZrPH2mRF0G9T8trwcX/cMlKQuGk4rILbzHMY8A63lSC3htUh6AUNoUe4CJtVl1yrRkdHDTPedzk3ozYsGayH7pj+hM0FxFe8EoJZrnIcmCkycWpagmhQAbnYFrk0hNdnq4dwElfulfyI94qeD+PqEe/FtLbaHzafNoSXhdmCj43fyUfEVWpZ2ZVNdwvA1Y9XuvLFGG9DmgbzkxKkBXTTkH5fmK3LGmn6xNbVYA/uReu6hY08ABDyYSxdEvkw82Cbv6bC6qECkEE7Jst3Qd+ze8zY91aRuOQ/fvcLzZWpe8I5/IvLaIqamzumlVn1wlDRH1gBBQMHLpEb9npyhW6LcjHS+sMrS0ir/s8j5FpWfnOlAVqWiSztGa+puivTrEkqT7Zslj/hwx6eHXJ5gpU02Fe6lUUqR8jRgRpW7RXsspMX0OUxs3E+ULLAKz9td6YZOCIjKSQgGxBo5UpOKzPqTphLaY3Dgv/NtsMv8qmk9knFQnON1OSC3VuwNEcudX2UCbQ+l8en5
      REVEALGOLIA_KEY: AgCFGhpMLW7vvdie7NFMm35JWrqjvewEiXJiBeNaDEbjMDrYdy6rPkPz2XG+SWvzKn+Edo7DjqkoK376dsqFolV6XN+IccHyx8xRnb5R2yvIk3QzaW++hMXJS1j7znUzNbWB8laECmZ2dr/W8GAAyr6X9pzlGHyC1DwJ3jtWU72/IjoNZbCod0/7YqM4mo3kEGyL9mTnBcF+zIyQNE0Y7phIHqAy0cEVuLNICWEaKQwMaRk9GqOInH1ZuySicWsshMm2TtLsN6I+m5Hk8U6jMtUuUi4ks/t27WKvgLyRz2PJYvXPJoubJn3uruYAUaBOiF1JdRirVPfpq7xC2/zbV0KyoLyUxXAxzgFaMY5JNzcE8Jp4HsRwRT9vSiapDj8XktuDDU9wtJQ/tNs1SxApOBYTflsBo6ykTpO9XOYdzeHqHvy1NUA1ou1rqTcV3UOIkBteJ9XJUoS1Tpgk08uD8hBf/W1KnVkmmIC5L4DOyxwp67HG5AJhxXPqsM3CiBup079tXDe6yptk1Ipfi52/W6qmikLP2EBzg3Bo+8vJUvxMO9YBgqBaZFwTcYR/JWKbhb9znk0zXIBWqykk/ObWApBgt4Tzb7vE4bvv2ll3+zM060cZ0hOaolL+o+TL/DB9WM2KQuZcfPhdy3IZpkCXuCz1IQ0lGHdda150WC//rvCa2OEvOx/dn171nFybbOK9LqvFH8yQh/Nea+Q/9XQk2T4zCF7iMJ9QLUviTQBex0MWag==
