apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: l3miage-algolia
  namespace: default
spec:
  encryptedData:
    REVEALGOLIA_KEY: AgCjMlMLbpp8c8bawET8LZ0zeBxdZ8ge5KsAPOLElMzK5sqqp6YuGesJfFodlMqmMv9oHHCogLBJNxjUVCBpfy3cCTVStFoOQF35RLygn0njEOk818KAbzJYj6nt+M2HVoGK5h/76fv7ui+GOZBFF2kVhwXivSbchMq3zWAcNSKTXgTsgG9isI1SiM9/3Q6FIJb4QgAt8Jq37N7M5yU1UFtJw8VHjwW57IF+DlcOIRARe4wvkqfxM6d83wzwN2hwQpeY3MPqdZ4/IpNqntRHSaD7t/eBq1WKKznkh5d20CB/TkTafNZxcYiWZ4r0GIaa7E4I9b21+ZEYjWVDPENo7IL+3TF3SxHC5FWLnPVdjkLaEsdArAME0LAiewT3Ujt8GKY3UW1+HsfzbG4MKHNgSF2qOqVMjQ81AWpFJ1WomfUEZ6TMu2Lu74g1yyC9/r5+NMf/02wTWSputAYLu+GafGZQ+gPud47Qi7urhUfU6IKE+w8Ld69YLGNMMcpO7NYM5lGYlB92bFBICw4wkQp7ThUW+qZJJbBUlrMP43n8RRP5S0ddn0MdSuM0m+MPAcQkErAdZLMuiNosxrCf1Tzy13yNzUUjvyWSzTbwL5Pxry0lBaI1lTKBU7pwJQE0TZmmhFO29itslk6v/5IaXIZv/dl5x2FzmxviqrrHq1wEVQ+ddIZC8NJE+S7DbaX1vaYMYpU/aLzggBIdtd0BjpGWcBZAZJJS7D6ktCalhVMcvrlC0Q==
---
apiVersion: batch/v1
kind: Job
metadata:
  name: l3miage-algolia
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: latest
    k8s-cleaner: 'true'
spec:
  backoffLimit: 3
  template:
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: dockerhub
      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: algolia
          image: vibioh/l3miage:202310200900 # {"$imagepolicy": "default:flux-l3miage-web"}
          imagePullPolicy: Always
          command:
            - /revealgolia
            - -source
            - /www/doc/genie.md
          envFrom:
            - secretRef:
                name: l3miage-algolia
          env:
            - name: REVEALGOLIA_LOGGER_JSON
              value: 'true'
            - name: REVEALGOLIA_APP
              valueFrom:
                secretKeyRef:
                  name: l3miage
                  key: ALGOLIA_APP
            - name: REVEALGOLIA_INDEX
              valueFrom:
                secretKeyRef:
                  name: l3miage
                  key: ALGOLIA_INDEX
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
