apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: l3miage-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.8'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: l3miage-algolia
    image:
      name: vibioh/l3miage
      tag: '202204031111' # {"$imagepolicy": "default:flux-l3miage-web:tag"}
    command:
    - /revealgolia
    - -source
    - /www/doc/genie.md
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgCNllg1HrZL86lnd1fxl+Z30OFSIRLIksO+3zIuU8BEfeT8Im7ZbHY0Ot5YpfkrTX4lGJalxfHn+hdDaPYuZI28ZEp+xJllgEIUnNs7/gFsFO6hNa9JTvMm6ie/Y8SS4YmIKbxa+nXDH3/J4FmdLM2ZAJ/HFwVbefsoziBqItmu+QXlzCEbwdDwOQxkwqyU/WtLuNZ45uEzmF0y+RHpcwPcAWvuC4illezilfRW+VSaInF12OZ26Eu0P2CW6mP0Hz4BE1UmY4OAX9Hng3vVX0kFsbGhed+f1ET7zJOo6D6LdGlV5g3tbxRvpt5k3Tmu5ZG4FN4A8ehR011R0PxggdC8HgA39VWn1GAC57P9ud/2wSi9P2Q1tn6CWYzPDioBU8iAtgKAP7YCwBh71L0//6xDbXW4nEQXQPEKdkwVvIYbHxy4FFeTlHzKfzFyhcpCDjD5nVr0OqHJCL501aMB90qghhkeUuEOQ5geGVcANk+R9VuhaK+bTRI/30GTDt7sVDYZ+oK1rtBwGxVqRuK1r1rVGEINzSp7Gz3oCDv/RwfUairau7os1l6Qhvm1AW2TcTEpiAgd9ZDD+MduNL/D3HaBW0SUyCtBwhp28ApN0WLKkfAyOnu1V3ZlQ28UWdVinzmwOomof5WFpnv3WATGKSnZyUQtwTzwJcQn3321R0WpUKPNovnmnH3jtOkxHv6TvQAArwnUpfLV/cxN
      REVEALGOLIA_INDEX: AgDcfWM6lBrty15GjpuMo5jOMuky23jYtQR2Xt04iGEXqDkM+UwHZkJl4nT/msssL/IJ+Z4vLq46f0tw/2vegBSUSIcVctu1hxxeHntgJhQ+8a3Ghpf6wmxiX3o7AdsDxmiA70kuVcMo7aOdnKK3En4m0jKAdhZAgHrV54I7q5keFTJBThWUL6hBFARj0gkeu37oauEbPobAAApUwukZ9cqEkhieA18HQu6sruyDZt3kRAPzANhcJbFYrgYyK+5zSpuSSeZLM7NW6NgF449MwRBPb6CZLc0GLPlO76r52brohw9PbNSpaFZDWC6np5yTmdJPo1MvJlZKPoXH2zF/gID92hJxN/Cgv5Aa2thVsSX1kae8zeZcCOCFVur/7ilUVwQhqO6cJUSCXiAqSwAadVwriifrf/zkvu+SGD2BXOvd8P+C63uSZHbR0fLPNC5JStjNDOBUyqwwTd8xMH4r+w2jBwa5gLCbLGYEBU3Qhrr/fUy4E2ghufmDS3m7mrjC+MzvBiFQLFQQk8M71bZz8JERpEc+fsRC+d1XpHb/R83smUUJpAo01PrY8vs/PM6MhRh44FO7//azjw4tOemHdtjlJPSvKSZcxGyvZMO8uLHjqEkatSh70xEb1FsdWF5/wG0n+wGX5+nJkZWA74n1tFZ3ocnSbfJPcwDfCBGwJISg0Za8XrWS6RNrXCjPcD6juARaad5PUtb6
      REVEALGOLIA_KEY: AgAwSzkfTA404M5CzWVZE/gJ3dh9FiXu6oJsCEsgSX0AxU46ia1SGxv+CIntrJ3n536WZo+SnbPZnXAu85wMMYFrc2flTfqQ8WHhVYlmEvR+M0LuKzzi6i+BE12DZQwvXxniLBq2LlbIsbK9XUqqhGCBkkaTrfCgPjqNcLdvS+Ok84XuVbmSNZA/5B8vX8cTViEQScFrE4RLTAZjiHWPXceJVBDbOgoH6UShksLPFOOu4Sn1579zT5FoOBL6fLCzBGapGczE/X2jwp4CsqXvC1Y8SDdbdC8dxkh/63PgoGcN4/tnJsFdFBy/XryBkyXmsQjvh6L6szIRu9FjmCzA/IlfBxeMhY+sRh+5X8CtPct0bG3Fu5mNTjTJpE8Ijo7co8LkMeUs7pSVes0o6VJPpm0YM1Y0X50FInA7HASYc7FqMcM+9Ef/1+PPGiEcFk9poQLcRPalBSxcDPciGVJ25qi9OQnI1a1LoT2MdMm/yj+S824q5J9Y3cGS5bOmSSeez3HGomOqvWZBaIzBhOWe65sSYj+mQ8mZBvIZvBDXHwRsVfOAD/TcOjSj4i5gGh1Nnpy0ov9Pn+Q90AYMxlHwohB5DPkD1Dv0wp6EMceNuvzGhwFsUuYeePu8Ny/oNE7H8e+rOKuwm8/eeNe7BlXycksCAKdokHsejbI43nViTgJjeiqwXypK4fMJmmioaH+wt7IWR6CCbMzylATpeCv4GfnSqUqI2vQH9SHqpqJXwO1qRg==
