apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: l3miage-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.8'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: l3miage-algolia
    image:
      name: vibioh/l3miage
      tag: '202206251605' # {"$imagepolicy": "default:flux-l3miage-web:tag"}
    command:
      - /revealgolia
      - -source
      - /www/doc/genie.md
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgAOwWC1GFnuE0yjUuyhDn0xs2U7Yn1txaNEqJYy/vNHawuPekFmNvq0IOZRfSuRXumvlZy9c2Mj3NpTwWPtqyuEOvSVhUrDOy62aEvfreiqBsPRU5HI001ZNlewmI57onYMS0rt/UHXO3PBfdmVXjMmO+nRw6AsIFYLu2UOXYzh5UdPaloshEJkTBQhtFWHIbU3HFW42un1ngDPsiJoZGMxz8E7GQe3SCpX4IdzzYStqOs6Ok4uvOuNmN8n4uZqHRgyfd78v4A/ZEFyZYTA+FN55qEyRqyrWUK49eenESU0VR7nPvdcRDoX7QubxTWAfZGcEDSCpYsE4wgMJUl8KYZR/NAXRc0yHgy/etZ6uUfd/l7W0SsoweVGdaJpnNuMP7Ox/lQCKA2adUn9IcViXI/covAF86IMxr+aJepEva/7samwEXdghvzpBPnwod5vG+oUj25C4uWslnT42CG0S6+LQloh1nqrcPfP3YucdIqV9TYgok9IKzcalmYHE1pLXnGqwUtccjKvlTj+BuspmyrvZDTI8bY1yg2lH0WGHViwEUwTLXXIWBE++gAe7fkWcj4hDmfYuDeP1YrGHXbPcYsm0Q94KBXpN7PgdMu8COyQgorAfxJRllGadJX0emzSLFbYMWAiYgPEG1tvnxkuXXu57wZAiHMpgZRc7d5lNOdH52k+uUBBBhEUjd932Ug4UiaFeCTsFt/9h9fU
      REVEALGOLIA_INDEX: AgCyEtUhVg/3LvSmAcnurpQEC5s15Q3sdZW6tfsSoOZXyZtH+tBWtvw0HyXIrSPFlLZiMpDDwAN5VYZBhOURyMqQeSivvziEA+R8lN1OToTnIFi880D2NdlIsq2NWxvED1/qUjrKo7jabRtw0ioyIkpcev5cuk4RT8647znmusT6mRiU2JCR4J7CghEpkhmsZXtrikyswz94+TTwiFMnD2XbJMGMWz1IrgLJMexgzWrVt+gFYebTxDWyiaNe07rvO3xGSte+jsBna4nil+vyIV0zC1iSh6t84tyQZ8vfWIZU/qBJrJh70cns0/PfAKpuxP1b5+9CmHOEL36wr9uzhDG6ya88j5DAVMniAQNm03JynBVaN3OY0Q2lgOuWz1i4KESBiQA3j1Qvw/p41Q1JNbh/8GJlvJG8v+mleSMyzaelXYqAF+jBH124tSIJScn08oleZJvDKDOfPg+Yq9I2VixyDSda65YFZyAV1nUeSKKtNOv9vRcWPtRP2tcCEr8M3HxikMhfOIahpSGjHp3BhyA9lJPlGt6VfIrmQy0pu4amN9Y/3ewKAdsOHkNCjGDumB3mjF4+keagOG+Dg94aZjRfpJm7iDJRbfaVoGnS7tKpogfG1qOQPu8I7yBsVWuqCL6lrIk3Xhz5VAffZoW4d5iC+xhciIHivxlSdBkqm/X3vwVoGG/5QVi3uGC/UUs0Wd8isDQcEs33
      REVEALGOLIA_KEY: AgCFaslYjWOQYnhhtYAC/Sj1OA5RF/y+HdAneGoZBj+ns8Cq/IGeHs0AP712xRt10+R6wZ3zOCsceNOXHV6SVO4cLRypvLTBy8czXjBfFA3Zni6P8L2eJM4QNVDv8kMSpTpt9tYa4KfqGntqaQeGTHWHfMANn+Apk9zxkTvo7x1GBN2LeYdVSBPVBaHMpq190lK2MVJeIMB+oxADyLKcWTbhOGJnlyoC2Wt1sNOJ+htCAPCk5/h5aPLRliCtlSaHBe4551KgHmW3JzvJNtYHIyZVzs8Cx4JWQNTTzaKsxzuix/yp0BIBSITdAy2Yc1Ht85v/9F+3kWSsr039gfSeUKp4wkfale2l2ndXZzGmdwqLsVyy9ilg8DzYpRTRAW+/27AcYE6sFHosf6sOj7tUjUq+94Kg1Yiz/1FauF3iv7lp9jOGjD8c1onNCATcllLUaqw+AduhHEPnP0anwcaSBMEVrgvINbGs6wQxeMfzghq5MkTM6/LSAQFXC99OcDdj7RuqDMgWlmxCxVoDqHQnIkBjKjVejd9BgI6OZJCNDOmTBxM74wcBIHpUBLKiZIYucsSrOoHjeR6Oy0/GCH7TX5pMIXUBoSCdhhpf4Dqfh+d84wvXDdeg8tcWLCcafmXGrQElDgtSV0EuUnTdpI+unWpuL02IndWMHPkbDykOTqUk7/nbnbf5qbhFGJFeWm0A7orZNvILnbF8bivG8QjpstM0al/9YHLYqm0uED6SCoWJNQ==
