apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: l3miage
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.81'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: l3miage
    image:
      name: vibioh/l3miage
      tag: '202206050731' # {"$imagepolicy": "default:flux-l3miage-web:tag"}
    config:
      VIWS_LOGGER_JSON: 'true'
      VIWS_PROMETHEUS_GZIP: 'false'
      VIWS_GZIP: 'false'
    secrets:
      ALGOLIA_APP: AgCRBcUhFeokqSjy+AHlx/9D7BF+wNfI4YZqXU9df0+WcByTcfihK/cQyuOxrf5i5Mg3QoBmicV0W44HBWcdGsSoTWcnogFUjZ+wjxGsI4Osuv9oCZuOLYF3IV2OV0x4GkwT/aglhVApeT0PCqvANf1BQbgAng7IADsmRaCEhIy0E7pYOdreZ6arDqMh1q5DdyGnYbNK0ScSfOX8CyUD7wTjMLP+rqs5dJec1EwbX3V/SsucPEsSYOvt5Y/3zGD0DP+LBfTt1TTzBSj09SHISi+4OCJoevQ2zfbUYDDYl5R5H22A2H8TMdQB51gnffKr3W5UySSVLvIB42yfle+Fup/h0QNWKHrNXZ8ROU+u0PZfdMucPJtrq+C/7RpV6KnZzwbRS6wuqF3hFkaq8HrnysctZPq5ZO/sv1Ka/IK9Bmpn7/JHXxObPxp8cAo9wtdT1RY0kTSW+2wM3sPtLBYu2a0N0EgyuGeSbvC2i3v03dpQo0U0TlYnKy23ckyCMqaP9VmwhfE//Uby6HK7RDvTtMM6R5lnyWepffbQFiuGEukAzcr3lNqwgCx1/+AFX4MxcsxMeElR6M5Ft70ZmAVvlT5ppeCZlUqFZH5U77QFLcjRNdDOPXHHBGaeGtIBZhUNi2MTN1aNQ2YRjLkENV1u8E/9XzdFUVnKI1ZqEY4SAqFJuKTjcV8TfYq+paezGKF/4RYNOI7zQ08tI60v
      ALGOLIA_INDEX: AgDbztfj0cAWqfK3SCbfRa2crxY3wG8SUd7lDO9ayFno4UY18Mkld9wsRi7ITkZBLH8oVWcUCdeZXyVQvMlcQDTLE6++69UiGB0ikESJ7kW6GRnmvewn/NfbeQOlxs/Or7CCbr3WcAbyMGKZxTZ9UJN02aJTqFHtwMBVezGJr5jP5fzFOaH1DQfYFSor4aGEef/+3EQ1HAsHO8B4U8xj0wWzTVXtMk0vPnaCuqHxPGnHC+Zn41rP1Hpwm/Y3wDrGRxJ6XiMcSulDfmUrKd+5O0jSVaGFGuyfMEf6axWkBRfBehNOcj+J94Vq0rPxL0RkkSY139XpjU/4VoKFy1Skv+U5J1/guj53Kbwkd6LcP5KSOHymAuNa++0RsLNrp0zEUWVO0BoHN3ywCsK41be55Tz6Hz9oGlBA4w5IKz99RQ+iPFYwY4ZQYTNUGcnapFHvd5BaH7BHGms9OzmPqm7jb0MkPvNARhvan5JSdiThOCJxuWOqwdI63sLblttH3QqtOof9Ep0va4Hzqb5AZmPErsTgD44iQfOsXZIr8Fscr5EZzPxlZTcwDeX1Fx7wXuP44coOzMKBYQcRTPLf/qKofbfEuFOrBR/XMEwS9dkl5D29ZfmPmvJR8b0tafDKWDBJT1QcTBQuwsjVYqazc9g8CekHtwCmgpIpia6okNynD/EJBVsaMVwiVVhO532IxMe2IgDYJq9mtfJT
      ALGOLIA_KEY: AgDiUNwETA04Jok3mkl8ILJSajShJyqf8mBScR2fPyRYbGkhn+KwHIfr8thSeY43eUwdoutQVLl19HpKZSNnHC/Eughi43Ysfpl0/AS2yHPCbh33Wr+tmJ8HN6EO2H+Ql9yxitObQTUaPbT80nzdb4uN6K3rDv59bbMCiq/+WZAWvzNYMCSV4M9mE/olpeC1v4ioNOxRNP8Kp6xl4DcmW39eLCVDOzZbXRiupTqmZY26jkD+KLfRn9TGdI3YelbWhFzT7imRqsOsHAWO8p23gEyIKz8/odM92JdHos4X3ejS6FukPCVePl2w6b/Fqmcw+by3gsRH1yxdEtq8fET1t4eLIuuQFg0GlazwmPGBxr/SOKo4oYRoIMJS/TKmGh3LWSy1KXlrW634psSAXpMB15+HDi/8og2TNi3kutR8gIP5RitCefsD2ta/xenfAZlaA6/XsnZUAp9pgKIobjLXhxedz93Ezy6RTQhjIBPjHdo3nrVRv2Psh0a5p22z++3JjnkuqkUowfPuxfy+4uAyIwZdCUgDjAmY52IMgq5DX4GJfFB2VXbVhnHdGLibK1h/4YO+Wz0skqvJQmmwpvHa1xDbg5CfxhddxHYhuNgRW6ec22SoQZN85wNh4hZi+VZ52jiQXnyaJh6kmRR7UF1d4/qtk/nIxCr1jBSHrH9BkwGhUyZ4qFEoTk164OQDm1M4MLfu6Weq1Nl/65mgg3eUDd4gM4YG0SP/gxjB+6KcJ6yD8A==
    ingress:
      enabled: true
      hosts:
        - l3miage.fr
        - www.l3miage.fr
        - genie.l3miage.fr
      redirect:
        regex: ^https?://(?:www|genie).l3miage.fr(.*)
        replacement: https://l3miage.fr${1}
    canary:
      enabled: true
      url: https://l3miage.fr
    pprof:
      enabled: true
  encryptedData:
    ALGOLIA_APP: AgCK2w1tD121lN62TCmOhfM3kINDqb9tv9TkYrtWg1BRU/r++I7nTAqlx6d3cr1kvxKvJ0Ps/PHNoU0uy/zBkmkBwsnBk4kaJl+SGzZy/PDd95v9hzWmL53vGvUyqbOiVoPrGDbAH7Dfu+gw7s6tJ+fjiBxzNJwUMqdPZ6vpG9JdP90j/phLeSNx61uAzUSzTCCG6AO2hTHFt8zW/uRir/KklMKYxtp4p8gmK79+9No2RkbBSBhLRH/9klDxkdRL7ALadSHHFnQjLGowxA3yvAA1x6v/FYh0IIAPavvZtro4XGo1zTh338K/wAn4PsvcAJ2oWjb60wKxzHVZ/jKlgVhiB6xYPPURdRRH0HnDAtt4cQlIxeoc32OE9RwusyvyemvVdSQQc0kKuQe6k5Ht+24qs5EZr9aHL1/h3B0IStrq5aT6GlIYy9amlT9DcY79GyraqOVPbdTCa/M4YoO8fvkslNUxZQ025sxGWLY+RXulymyqXngkEEBu4bsU1RI5aLKyOMBZCzyObR5NzjWq2dASTtf6W15Zn2Z2KYPrm2fTFmSvSbjAU127NUwgS8l9D1p7kz/s5XSDe9p9DVIV081gCZ0NLTV/DlokL+qwKZIDQywnHbYtqhiU2B8HXaDwBhOxlMYv3Ur4dmu2MaXwGP1J/uR84RrYMgzTXf3PRuMXjCp/gCDqs2l37D3zfVENonu7iiaYqRbVegA7
    ALGOLIA_INDEX: AgBzEpy5lyVAlXAAwQs04r8cWT41SviORJpOaDwq2V0UaykM526wOENdECUzjHWz0Wl3xbQaqzhzQEhAIdu9Cc/knIq/rviEDhNy/vVzx2aSzUdDhKbBObkfxqoR5QqwrwwF4q+68L+tY+AH8KLLXb+Cm5KC2KqcS+352WyGFUydi1vzEumVBRzOr6IpPk4oqaqkaUWspo/DsIRShoD3ucztunfolo8DvVYldmt0jTEVVnp7LPVJEUXyftENRZl6aco/sRhiBDJCKMyH2iC6WzuZV2/UXDIrWKoa2hC+KWUQ87zh7stnKXL14xw8bzCAIkw3IO16Wsm9oc3biIXwXzyKbjtyOCleptu0hu6MLFarZP1cLEiI2z0USkbQw9Q5jlauVOUHHZc+RWAUWcgYxzu+eBMqgSfMnx3Uyqhj1JSt2U9r3jkQ5ojlG2CG/clCqzIcOs+2E7CufIapl/b+VB4JGbemsjKzyJOy2/Ufn1G9g6745dS4GJ8yGkxRT+SoqfQ+WYucbpsoo6AkD3y1dfD7X4pdfsyUJ6SkYEcerNL3BR4d1gE+4m9vJVDyP3W6z3fpJhoN9Zwu2173MMnrrQSuvinkJo/uD7+uZe+Z8fCsCjYwhsK/iclV/ODLXtLBHYFA9r8AJAN43Xs5q2EDXGa9bLM+c4Pyqpe2AhgEDA6qo42CecbwZJh1PZ5kEwLw1VDK3lBrpRu7
    ALGOLIA_KEY: AgBGLLBVZEHCOE3XG3XiAkIXk2083nWgJwDfCiJ31PYCFSS3Ceam5gV0l4xRg0lsVX7xC4YnsPPtWHNHinAbBV7RLx1BU1/LcuX1OypzZ0dzlr7J6jTtdKH4VFXDHnW9xY3D1uyUZk3Dwq0aw75wqI3HHnKxHPiBGdnofGurLN2cQwkZHVO0Zkg9f4OLH8Fhh+f7mdTFG9BKpLfFyJJVPZxcwYycdOhaZu9wgITVBbdtzwNhPPV8MHzW8a8a2sdCXDAGup1HwS44pU+pPk1xVXFQYqp91Lb5rZM/Sr9ZiUAT7TmgiD+Xk7ketvKCliVodEFT3vqzATFxc31kU+IrlPNohj3/AFCwv7ohQYmXldxmvwhdgtdhhL8gaWTsOjWY6zvDhIiqfm0wo1RFhW7AcmR4IUd1JLCSNqMWQW2deeb1B1vHQav0BceaKkgSkFA5OTTCvndYhX8ikssNpQU2ebMcYmfvlr65MMq1S0vx64dsz91qMUIxfRcDqZvK9xAD3CuXZAdOavTt1Leg0TKnLdkwPkZC3WbQKpzLGBSzqlEs09+Bew+YidrK8tMwoF612Pg1a54lf/dHFPRWMQntu9jsp8q5cBhxjdqOMWEwFlct13oBvwgtQchhIhy9mfEut/XFw1rb9u25nNqdXx8OZjCBPIJaGfI4bA9WtJLmYnDL9L3ZIG3k3nJ4ddZikL6DnPZpk1a/mPY842kt2+ohMt/5x5t9SG4/lQKKXDqOouWBHQ==
