apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: l3miage
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.84'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: l3miage
    image:
      name: vibioh/l3miage
      tag: '202207130946' # {"$imagepolicy": "default:flux-l3miage-web:tag"}
    config:
      VIWS_LOGGER_JSON: 'true'
      VIWS_PROMETHEUS_GZIP: 'false'
      VIWS_GZIP: 'false'
    secrets:
      ALGOLIA_APP: 'AgBKfhr/JyrCuYo0J8a6W84TdGKL6gLiK2sIsPfVYFQhxGIliT5p2qTrpmW9PHM29hxybHIg2BACU2VgFUcyzbUyFMIt3ZFK7EuJ3hfEjB9BiR0Ir0yEtNGw3XqrKb5Q6grlJfB5GVnKXMws6VVSoAmkA3yttUngxl9P7kKFsvRMMGiDSCcqb2KHOktGZuJotmlHg07NWixI7Nvh27NGzqBcT/yjYnLiGZdoYFQTeLT16OgyKKAZvEXSZzjCMT4XHB11wMzwuuLlx8f9oXst00Qv1gGx6pHtKRTgoHrZ2aRlrfkZne4c3EWG2235NQtDhT9qphI7qs0V6y2GOsvKhsRNQDUAiLCBTntkdTmjbYM9+tqyIb/duEJgH8nmKjIs+ei6Lo7okC2ztYpFVQq6GwJ+gUqEsfoTAwNu1FwSpYMUrmsgZx6XhwAUun5PnO0vkgpmuuiXcRRpKiwgt98rRbIE/WrhK62pjKqDjmPxg2Ql5ysFv0sG7wU14msWOajpjqpcx8w92GZ3LGvkefEbaPTCnH3NSI3/yS0PeWoKnGaXUiNBksGa2BtMUBIEmsCl0A5Js/0Iow56ft5WVtbiXDmzA9+IqyJGzcZhXLEEVxCdQ6eWrTzDZSpBVsZlON5zdr4kMTXPU5kMSNUMh17wyJhJ3OaEGagUX4NrhFCHYg5CR0oJ21i+RnFwBDC2XBiIaqNI8QKAKoYFExu+'
      ALGOLIA_INDEX: 'AgCQCpIdRMrseGroNyqR1g6wiWOxl1+4WcMKkadfArQUT7OigmWw20BwA8HjNXXyHCKcJTiwE/Tw4U5SXetvMjmUwhsTnRRn4ebv0MRuXv5DZP4Ti3WXOCfZyFhVOe6dqomWs3skbQIC9TTwcdn5rXdhKyqOJHF3JEdgaoz6gtoYQbf9NPIyWso7gTgbMqcbif896d+adUgvlJtddvcV28f/tHf0jZXaQQlTSRMgz41xCXp+88wS9PK3LbEtAEiuZsIdKBUrwOqMLuy50E7zCHxBucsC9T/vI5PAk31gLi2zoSAgPIjWNkRZ1foL76NRfBss7SBPVK0E3LIKo1fPEdjGoDw8wXs//MCcFq1D0v1c7BN8CMMPMMCVaR0nbcVt2YEvcpm/O9lv4hvXtLFt0QwQUJVy8NOiUwN8OeHZAhU15Kq/PglC8BTNAoDEpBmxyGOLZrv8alovuj3nWBxs7BgUox7A0bwUmfVkxdaYjb4GrkA/dM4Rk0rvYk48Sl6jeaZeE2KmsDKO4gplhYZWBLgIF867q5auy0YS+yQ92YXBD8iVUVj8PQb9klzbwFS5INkPqkj1dFymTvoH5RBrcVK4hsQ2Gakpc4QrJZQxh6VgPkeIG4DIkjcp2gGm1DDbrjl7IZ4rcwrtcS/qW4dcOaQZWmK435W1vtHoL707S6UI/ln82fhXX7a0o7kv+i06uqCSTKT+j99+'
      ALGOLIA_KEY: 'AgCMC6CaED6ds5ibq5phwRP/fYzacrisjlTrc9xP383ECMpoFTW//L1V9ChUSU/91XKYrnYoJsnfMy5FLqbCuXbqjfzlO0lEQKPt8dvAjU0lFLtdm4mujWj4wdRsxLGi2ZnnYbE4fRhkeQHbpmI5rZZKDVQKbnhe0kvbsEPjmf+qXovuxcBBZLwFtEnSThtCjsHqIt7TUgaAvVq/NE8R/lXrvvPr58L+5jV+BUVNqSboW2H1fZ/HYppB8j+7VxMUWLaVatAvt1DM5Ylcs6k5dnoaJGDNjI8iqQCi4vzQVmD6UOz8PeTrzf4cZSuPSBiySuBH75M0HBrVoDrkBKMtWNhD+KvEX3ArGLW8+sl1mU2vyAK5aHSNg6oUzku/Q8ntisMQc3pnUERa11JZ6uoXeB5NLztX1ttvPtNe019hFtR5fFHCtc60cHt7P8QWxK5gfSze+spY797qKan7JK7cZCG4+dfGfkAlbWNDLdTniESXIoXckIAfUTUQrtP4BHyYe4oBwvJg7FLbNQLsIHUVpqxn9daMF0MGWzSC7vDhRQeP8pg7GTFbkKz3JeUzh78pMulO9a8cp2wn+z63pRQoQYlxiL7LuKQilnFbDRidiWYigP2n3I2XeYUSpqknXGhIa5Ji905fwG8lvTLMFIu7BigFjGwS9/nP5K0rRENFWBfdx19U2Q3PJ/j1XsATdzyKUp2BNnIxL4ZXA8yM4UpjrzT6VP+UUAI5eYQpDn6Xh1msNg=='
    ingress:
      enabled: true
      hosts:
        - l3miage.fr
        - www.l3miage.fr
        - genie.l3miage.fr
      redirect:
        regex: ^https?://(?:www|genie).l3miage.fr(.*)
        replacement: https://l3miage.fr${1}
    pprof:
      enabled: true
