apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: l3miage
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.81'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: l3miage
    image:
      name: vibioh/l3miage
      tag: '202204170917' # {"$imagepolicy": "default:flux-l3miage-web:tag"}
    config:
      VIWS_LOGGER_JSON: 'true'
      VIWS_PROMETHEUS_GZIP: 'false'
      VIWS_GZIP: 'false'
    secrets:
      ALGOLIA_APP: AgCRBcUhFeokqSjy+AHlx/9D7BF+wNfI4YZqXU9df0+WcByTcfihK/cQyuOxrf5i5Mg3QoBmicV0W44HBWcdGsSoTWcnogFUjZ+wjxGsI4Osuv9oCZuOLYF3IV2OV0x4GkwT/aglhVApeT0PCqvANf1BQbgAng7IADsmRaCEhIy0E7pYOdreZ6arDqMh1q5DdyGnYbNK0ScSfOX8CyUD7wTjMLP+rqs5dJec1EwbX3V/SsucPEsSYOvt5Y/3zGD0DP+LBfTt1TTzBSj09SHISi+4OCJoevQ2zfbUYDDYl5R5H22A2H8TMdQB51gnffKr3W5UySSVLvIB42yfle+Fup/h0QNWKHrNXZ8ROU+u0PZfdMucPJtrq+C/7RpV6KnZzwbRS6wuqF3hFkaq8HrnysctZPq5ZO/sv1Ka/IK9Bmpn7/JHXxObPxp8cAo9wtdT1RY0kTSW+2wM3sPtLBYu2a0N0EgyuGeSbvC2i3v03dpQo0U0TlYnKy23ckyCMqaP9VmwhfE//Uby6HK7RDvTtMM6R5lnyWepffbQFiuGEukAzcr3lNqwgCx1/+AFX4MxcsxMeElR6M5Ft70ZmAVvlT5ppeCZlUqFZH5U77QFLcjRNdDOPXHHBGaeGtIBZhUNi2MTN1aNQ2YRjLkENV1u8E/9XzdFUVnKI1ZqEY4SAqFJuKTjcV8TfYq+paezGKF/4RYNOI7zQ08tI60v
      ALGOLIA_INDEX: AgDbztfj0cAWqfK3SCbfRa2crxY3wG8SUd7lDO9ayFno4UY18Mkld9wsRi7ITkZBLH8oVWcUCdeZXyVQvMlcQDTLE6++69UiGB0ikESJ7kW6GRnmvewn/NfbeQOlxs/Or7CCbr3WcAbyMGKZxTZ9UJN02aJTqFHtwMBVezGJr5jP5fzFOaH1DQfYFSor4aGEef/+3EQ1HAsHO8B4U8xj0wWzTVXtMk0vPnaCuqHxPGnHC+Zn41rP1Hpwm/Y3wDrGRxJ6XiMcSulDfmUrKd+5O0jSVaGFGuyfMEf6axWkBRfBehNOcj+J94Vq0rPxL0RkkSY139XpjU/4VoKFy1Skv+U5J1/guj53Kbwkd6LcP5KSOHymAuNa++0RsLNrp0zEUWVO0BoHN3ywCsK41be55Tz6Hz9oGlBA4w5IKz99RQ+iPFYwY4ZQYTNUGcnapFHvd5BaH7BHGms9OzmPqm7jb0MkPvNARhvan5JSdiThOCJxuWOqwdI63sLblttH3QqtOof9Ep0va4Hzqb5AZmPErsTgD44iQfOsXZIr8Fscr5EZzPxlZTcwDeX1Fx7wXuP44coOzMKBYQcRTPLf/qKofbfEuFOrBR/XMEwS9dkl5D29ZfmPmvJR8b0tafDKWDBJT1QcTBQuwsjVYqazc9g8CekHtwCmgpIpia6okNynD/EJBVsaMVwiVVhO532IxMe2IgDYJq9mtfJT
      ALGOLIA_KEY: AgDiUNwETA04Jok3mkl8ILJSajShJyqf8mBScR2fPyRYbGkhn+KwHIfr8thSeY43eUwdoutQVLl19HpKZSNnHC/Eughi43Ysfpl0/AS2yHPCbh33Wr+tmJ8HN6EO2H+Ql9yxitObQTUaPbT80nzdb4uN6K3rDv59bbMCiq/+WZAWvzNYMCSV4M9mE/olpeC1v4ioNOxRNP8Kp6xl4DcmW39eLCVDOzZbXRiupTqmZY26jkD+KLfRn9TGdI3YelbWhFzT7imRqsOsHAWO8p23gEyIKz8/odM92JdHos4X3ejS6FukPCVePl2w6b/Fqmcw+by3gsRH1yxdEtq8fET1t4eLIuuQFg0GlazwmPGBxr/SOKo4oYRoIMJS/TKmGh3LWSy1KXlrW634psSAXpMB15+HDi/8og2TNi3kutR8gIP5RitCefsD2ta/xenfAZlaA6/XsnZUAp9pgKIobjLXhxedz93Ezy6RTQhjIBPjHdo3nrVRv2Psh0a5p22z++3JjnkuqkUowfPuxfy+4uAyIwZdCUgDjAmY52IMgq5DX4GJfFB2VXbVhnHdGLibK1h/4YO+Wz0skqvJQmmwpvHa1xDbg5CfxhddxHYhuNgRW6ec22SoQZN85wNh4hZi+VZ52jiQXnyaJh6kmRR7UF1d4/qtk/nIxCr1jBSHrH9BkwGhUyZ4qFEoTk164OQDm1M4MLfu6Weq1Nl/65mgg3eUDd4gM4YG0SP/gxjB+6KcJ6yD8A==
    ingress:
      enabled: true
      hosts:
      - l3miage.fr
      - www.l3miage.fr
      - genie.l3miage.fr
      redirect:
        regex: ^https?://(?:www|genie).l3miage.fr(.*)
        replacement: https://l3miage.fr${1}
    canary:
      enabled: true
      url: https://l3miage.fr
    pprof:
      enabled: true
