apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: l3miage-algolia
  namespace: default
spec:
  encryptedData:
    REVEALGOLIA_KEY: AgCjMlMLbpp8c8bawET8LZ0zeBxdZ8ge5KsAPOLElMzK5sqqp6YuGesJfFodlMqmMv9oHHCogLBJNxjUVCBpfy3cCTVStFoOQF35RLygn0njEOk818KAbzJYj6nt+M2HVoGK5h/76fv7ui+GOZBFF2kVhwXivSbchMq3zWAcNSKTXgTsgG9isI1SiM9/3Q6FIJb4QgAt8Jq37N7M5yU1UFtJw8VHjwW57IF+DlcOIRARe4wvkqfxM6d83wzwN2hwQpeY3MPqdZ4/IpNqntRHSaD7t/eBq1WKKznkh5d20CB/TkTafNZxcYiWZ4r0GIaa7E4I9b21+ZEYjWVDPENo7IL+3TF3SxHC5FWLnPVdjkLaEsdArAME0LAiewT3Ujt8GKY3UW1+HsfzbG4MKHNgSF2qOqVMjQ81AWpFJ1WomfUEZ6TMu2Lu74g1yyC9/r5+NMf/02wTWSputAYLu+GafGZQ+gPud47Qi7urhUfU6IKE+w8Ld69YLGNMMcpO7NYM5lGYlB92bFBICw4wkQp7ThUW+qZJJbBUlrMP43n8RRP5S0ddn0MdSuM0m+MPAcQkErAdZLMuiNosxrCf1Tzy13yNzUUjvyWSzTbwL5Pxry0lBaI1lTKBU7pwJQE0TZmmhFO29itslk6v/5IaXIZv/dl5x2FzmxviqrrHq1wEVQ+ddIZC8NJE+S7DbaX1vaYMYpU/aLzggBIdtd0BjpGWcBZAZJJS7D6ktCalhVMcvrlC0Q==
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: l3miage
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.1.7'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: l3miage
    image:
      name: vibioh/l3miage
      tag: '202503041612' # {"$imagepolicy": "default:flux-l3miage-web:tag"}
    labels:
      tags.datadoghq.com/env: 'production'
      tags.datadoghq.com/service: 'l3miage'
      tags.datadoghq.com/version: '202503041612' # {"$imagepolicy": "default:flux-l3miage-web:tag"}
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    config:
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/l3miage
      VIWS_GZIP: 'false'
      VIWS_LOGGER_JSON: 'true'
      VIWS_PPROF_AGENT: http://datadog.observability:8126
      VIWS_TELEMETRY_URL: datadog.observability:4317
    secrets:
      ALGOLIA_APP: 'AgCn8+4FkqHgg1jXp0u5VVRLm+rtYjFKGVC9SgwLMWjTAYJYy1gPKKbP9CUPiJQ7m8rZDDihzSKG3dWkHsNyc3OQwykpzpuG1G97kW1amJGDDkt1y+QmmS3KOrFmd7vYCFMae2VADbiwXGm3EJi7LcPtedaA5u1bTARsrXtluIsBC7KhIBnhhb+JYw3lhQBkGUA3LwQIvbmcgyWMayjfKNX9mRrshJlsIBx0PltfLNQSkkHPUDuToxM8AKFxsRTOvmTLQMwz4qgoBwbXL27BJgaDyPMqY159wZBDyKXvJtl6wp09mFA5O2Z2fk52gEVYXCop1OGkSpHozIaL7cDxyTMgeB2wAQLN2An4Jf9lk5bzBN0AZj6UqnAbglNIKeMpNp4F6Kl5NaAdYLTscOH3LZFCZDQidCXP+FT06BPhQmb9oxjk+Pchu4k4DEe4Suj6h6bALg0k6xxkZI536S14AkgP28cJqY5TPSBASX9yTleGlnW7SfPf2FVaAja/aUQkzuRRxDFZSZ6dJrbx5eHeS5qH8e+84tlRNoANFrcIkfGvfbaLtcnRxj438oQ5oT9UQPU0pnJdl2TlBieLBflUwRPkuSaF7YKPQLr0179+zq2okPHoj7xHDY7T8InAlLxyERo2HiKAkno/Vd6cVYIr8w9GgC61qQhvB6lGOgMwAVUW68AiVb2kO+T8HJ5Oh53WEghl6JC5bVWeginQ'
      ALGOLIA_INDEX: 'AgAkJUis4+osNMqdCNcxQgJNcvOH05U7f1rwXj0pqHOqFOXLi30JBnmX0sUM7A8x9/CtZbzaOfHDH6my2oT2Z41HGTW6HFPP08P7l4oaoLCcuNHmHGlimOOsw2LQPemyVlhjbSCmdbBqRQLA0xHZ/yq0MhbpqyEh3N0cMBqQU8jyQnXqNFmukPvm2miviLUevyU5wErUBa0QlB0jdylNDXqG2OMSzY9n55TIlb0hHJmIuv+RvGpPRsUAzMnCTeExiuVYAwc+avcgcLZYVVbOZHji2wo3mZsu1oMn3eF3y1oH3AuFqTgZMOiE3b+n4WW9Zttk3qodGk1DhRW9mLDeP6sbcIFJ187JvCu98hDHIQ4sKfLziX5YmUL2rqsJHdS6C55Bkv4xqqsQdd/y9xRw64bRtptUmQyWUj6FSMzLYL3S58F68I3qny0bG0e6eECeNcuw1Vf7AuzoDUJ91mbheh/O2D7vy/ImzFXoWpUR95kZ9IXEWR3VDyvDtThc3/DYbBpSVXaZHIJYzsj2kqm4ZM1qk16S3Ik65K/bYwrezdflDFtWXPo69mPdyYZHUuvKSy6J4/v7J2ZySttGWPwJM3kFfF3kxKRd2KJCZUIySjNHKOv8cAtAKGUW7a2wm4JbcdzsJnKBhyxIOphXD+L1URJqTT+F2ovVWvrEoAB6LqyGtIa3UsI6l43+GxRusS4d155XQXd2+Axz'
      ALGOLIA_KEY: 'AgAmdPNX3ODeOPUARN5lL/JkWgJtSa5TfEmbHwI80istiqc0J/SFf3bCL/T/xMzl8xo3wfUFladxAMQwHLn4Q5rxkuDrxEB6yB1JZH+e4d65CRdlh+kxANL/qc+/gsVvYjX0HTPIeVbanYNuPH9+WYz1yS4syUhQy36GPBIkxL3IF0ItCmyHSwtloGxuhOJsQZ/AlkiSK4R+l8VVruY5Rt3wCxaz/SkeXDCaHcQUNQIDqfhunroS/xoggXPNuzalKkLOM3N48AsSxMQuosENsQdRx2bVYE7w40Hvht+Gdqj+ugxorqK33pjCDFQA/kJKqNIxqgKer+V+8kGelCcxpqKTeBAlTzzqS3OpL95ZfzDUNZRMDXsuB40hQxrjeV9fsePJO7qHK2IciskJ639lhppjYHf8b4STGe1Na/vRnhbvcEAxPju4WLeCHBbhyG3ytT58HqAK4Pb4Q6dXjguAGTl/2HQlxvcPJi22xi7BpahqHGIcvIImeRxiFowzetavG8Nwb7gEX9DUh6ndhGPO4z14pZF5y981T6Je8YNfZypW53JivbZVOIuqn3SiIPjoU8ysuRJpjP45nKVWVsNVDr57zG8gFqYTJxc+fZ3lQeHKtzdxj2y0cMMJmRyNs8WxoR71H7qI9l8BuG7AX+6XMGuqgoKqoOmwlchb+QvMtWrEXQS7PhqfZ4QIKhaHkGI9JIO8en+lmhDxgjSb6gT1xGJtt05AiUK3X96Ss+eZBMZdGA=='
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      compress: true
      tls:
        enabled: true
      hosts:
        - l3miage.fr
        - www.l3miage.fr
        - genie.l3miage.fr
      redirect:
        regex: ^https?://www.l3miage.fr(.*)
        replacement: https://l3miage.fr${1}
    initContainers:
      - name: algolia
        image: vibioh/l3miage:202503041612 # {"$imagepolicy": "default:flux-l3miage-web"}
        imagePullPolicy: Always
        command:
          - /revealgolia
          - -source
          - /www/doc/genie.md
        envFrom:
          - secretRef:
              name: l3miage-algolia
        env:
          - name: REVEALGOLIA_LOGGER_JSON
            value: 'true'
          - name: REVEALGOLIA_APP
            valueFrom:
              secretKeyRef:
                name: l3miage
                key: ALGOLIA_APP
          - name: REVEALGOLIA_INDEX
            valueFrom:
              secretKeyRef:
                name: l3miage
                key: ALGOLIA_INDEX
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
