---
name: Build

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCRIPTS_NO_INTERACTIVE: 'true'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - name: Build
        run: |
          npm ci
          npm run reveal
          npm run build
          git --no-pager diff -- ':(exclude)www/js' ':(exclude)www/css' && git diff --quiet -- ':(exclude)www/js' ':(exclude)www/css'
          sed -i -e "s|{{version}}|$(make version)|g" www/index.html
          sed -i -e "s|{{version}}|$(make version)|g" www/js/index.js
          sed -i -e "s|{{version}}|$(make version)|g" www/js/algolia.js
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Docker
        if: env.SCW_SECRET_KEY
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          DOCKER_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          REVEALGOLIA_VERSION: v1.4.12
        run: |
          curl --disable --silent --show-error --location --max-time 30 -O "https://github.com/ViBiOh/revealgolia/releases/download/${REVEALGOLIA_VERSION}/revealgolia_linux_amd64"
          chmod +x revealgolia_linux_amd64
          curl --disable --silent --show-error --location --max-time 30 -O "https://github.com/ViBiOh/revealgolia/releases/download/${REVEALGOLIA_VERSION}/revealgolia_linux_arm"
          chmod +x revealgolia_linux_arm
          curl --disable --silent --show-error --location --max-time 30 -O "https://github.com/ViBiOh/revealgolia/releases/download/${REVEALGOLIA_VERSION}/revealgolia_linux_arm64"
          chmod +x revealgolia_linux_arm64
          curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/main/bootstrap.sh" | bash -s -- "-c" "release.sh"
          docker login "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}" -u nologin --password-stdin <<< "${SCW_SECRET_KEY}"
          DOCKER_IMAGE="${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/$(make name)" IMAGE_VERSION="$(make version)" GIT_SHA="$(make version-full)" ./scripts/release.sh docker

  publish:
    name: Publish
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Publish
        if: env.SCW_SECRET_KEY
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          DOCKER_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        run: |
          curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/main/bootstrap.sh" | bash -s -- "-c" "docker_promote.sh"
          docker login "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}" -u nologin --password-stdin <<< "${SCW_SECRET_KEY}"
          scripts/docker_promote.sh -d "$(make version-date)" "${DOCKER_NAMESPACE}/$(make name)" "$(make version)"
      - name: Flux
        if: env.FLUX_WEBHOOK_URL
        env:
          FLUX_TOKEN: ${{ secrets.FLUX_TOKEN }}
          FLUX_WEBHOOK_URL: ${{ secrets.FLUX_WEBHOOK_URL }}
        run: |
          curl --disable --silent --show-error --location --max-time 30 --header "X-Signature: sha256=$(printf "{}" | openssl dgst -sha256 -r -hmac "${FLUX_TOKEN}"| awk '{print $1}')" --data "{}" "${FLUX_WEBHOOK_URL}"
